### PR TITLE
Production iteration (breaking schema change)

### LINKED ISSUE #39: Failed to write image cache / Image uploads fail
Not sure if an issue yet, but certainly a warning;
After deploying [v0.0.3](https://github.com/orgs/authenticvision/packages/container/digitalsoul/144580588?tag=0.0.3) to our kubernetes-cluster and visiting the NFT-Overview of RDFC, I get a warning in the logs for image-caches;

```
kubectl --namespace metaanchor-digitalsoul logs -f digitalsoul-59f44bdf9c-sr2xr
- ready started server on 0.0.0.0:8080, url: http://localhost:8080


- warn "next" should not be imported directly, imported in /srv/app/.next/server/pages/index.js
See more info here: https://nextjs.org/docs/messages/import-next
Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'npm i sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
Failed to write image to cache gbguDfDgRFyqDd1eqCRG9oFfVAnkcTKm3Ye4VNAI9xQ= [Error: ENOENT: no such file or directory, mkdir '/srv/app/.next/cache/images'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/srv/app/.next/cache/images'
}
```

I tried uploading an image;
image

The upload proceeds to 100%, but then the Frontend gets stuck. Logs reveal;

```
TypeError: Cannot read properties of null (reading 'id')
    at getServerSideProps (/srv/app/.next/server/pages/contracts.js:239:33)
TypeError: Cannot read properties of null (reading 'id')
    at getServerSideProps (/srv/app/.next/server/pages/contracts.js:239:33)
TypeError: Cannot read properties of null (reading 'id')
    at getServerSideProps (/srv/app/.next/server/pages/contracts.js:239:33)
TypeError: Cannot read properties of null (reading 'id')
    at getServerSideProps (/srv/app/.next/server/pages/contracts.js:239:33)
[Error: EROFS: read-only file system, open '/tmp/upload_b31972bc95c8abd1d9bee5ba08d07272'] {
  errno: -30,
  code: 'EROFS',
  syscall: 'open',
  path: '/tmp/upload_b31972bc95c8abd1d9bee5ba08d07272'
}
Error: ENOENT: no such file or directory, open '/tmp/upload_b31972bc95c8abd1d9bee5ba08d07272'
    at Object.openSync (node:fs:603:3)
    at readFileSync (node:fs:471:35)
    at /srv/app/.next/server/pages/api/internal/assets/[anchor].js:281:77
    at IncomingForm.<anonymous> (/srv/app/node_modules/formidable-serverless/lib/index.js:33:9)
    at IncomingForm.emit (node:events:517:28)
    at IncomingForm._maybeEnd (/srv/app/node_modules/formidable-serverless/node_modules/formidable/lib/incoming_form.js:563:8)
    at /srv/app/node_modules/formidable-serverless/node_modules/formidable/lib/incoming_form.js:242:12
    at /srv/app/node_modules/formidable-serverless/node_modules/formidable/lib/file.js:79:5
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/tmp/upload_b31972bc95c8abd1d9bee5ba08d07272'
}
```

*Root causes*
The file-upload generates tmp-files at `/tmp/, which is *not* located in the mounted /srv/app/nftdata. Hence, in a production environment (kubernetes), writing to `/tmp/*` is not possible. 

The same likley applies to `/srv/app/.next` 

*Possible solutions*
- Working without temporary file systems
- Use `/srv/app/nftdata/tmp/` as temporary filesystem, since this needs to be mounted anyway
- Create a two separate volumes /tmp and /srv/app/.next for temporary filesystem also in production

### PR DESCRIPTION
**Pull request by tbergmueller**
This is a PR with multiple features. Since these features are tightly interlinked and have to do with asset-uploads in combination with the rush to send this to production, decided to combine

- Mounts a persistent file system at `/srv/data`, which has
    -  `nftdata` Folder to store NFTs
         - `upload` folder for temporary files
         - for each CSN an folder is created hosting the assets 
    - `node-cache` Folder to store generated and built nextjs pages, images etc.
- Generalizes asset-endpoint to allow uploading all `assetType`s
- Rename assets file_name -> file_path

**ATTENTION BREAKS SCHEMA**
This has a breaking schema change, assets.file_name is renamed to assets.file_path. No migration strategy implemented, since not productive yet

This somewhat prepares #40, resolves #39 and touches #19

### CODE REVIEW

File: pages/api/internal/assets/[anchor]/[assetType]/index.js [hunk 1]
```diff
@@ -140,17 +146,31 @@ export default async function handle(req, res) {
...
-				writeFileSync(path.join(STORAGE_DIR, fileHash), fileContent)
+				// Split files per Smart contract. 
+				// This is a logical separation and also reduces the risk of Filesystem-overload
+				// due to too many files in the same directory
+				const storageFileName = path.join(nft.contract.csn, fileHash)
+				const targetFile = path.join(STORAGE_DIR, storageFileName)
+				const targetDir =path.dirname(targetFile)
+
+				// Create contract-directory in case it does not exist
+				if(!existsSync(targetDir)) {
```
Comment (pedrolucasp) [inline pages/api/internal/assets/[anchor]/[assetType]/index.js:163]: I think moving this whole process into its own method would be a bit cleaner, since this handler is getting too big already as it is. It is a minor adjustment though

File: Dockerfile [hunk 2]
```diff
@@ -19,6 +19,15 @@ COPY --from=dependencies /srv/app/node_modules ./node_modules
...
 RUN yarn build
 
+# NextJS seems to have no intentions on supporting a 
+# different cache dir. They do seem to approve symlinking though
+# https://github.com/vercel/next.js/discussions/35656
+# https://github.com/vercel/next.js/issues/10111
+# Note this is kind of dangerous, as it relies on /srv/data being the 
+# mount point of the volume!!
+RUN rm -rf ./.next/cache
+RUN ln -s /srv/data/next-cache ./.next/cache
```
Comment (mologie) [inline Dockerfile:29]: Would leave just the `rm` line here, and move the rest incl. the comment into `runner` where it's actually used.

File: pages/api/internal/assets/[anchor]/[assetType]/index.js [hunk 3]
```diff
@@ -114,22 +115,27 @@ export default async function handle(req, res) {
...
+		
 		if (!allowedMimeTypes.includes(uploadedFile.type)) {
-			return res.status(422).json({ message: 'File type is not allowed' })
+			rmSync(uploadedFile.path)
+			return res.status(422).json({ message: 'File type ${uploadedFile.type} is not allowed' })
 		}
 
-		const filePath = uploadedFile.path
-		const fileContent = readFileSync(filePath)
+		const fileContent = readFileSync(uploadedFile.path)
```
Comment (mologie) [inline pages/api/internal/assets/[anchor]/[assetType]/index.js:138]: You're reading the entire file into RAM here. The application's memory usage will increase accordingly during uploads. To avoid the container being killed for large uploads you must stream your file to the hashing function instead.

File: pages/api/internal/assets/[anchor]/[assetType]/index.js [hunk 4]
```diff
@@ -140,17 +146,31 @@ export default async function handle(req, res) {
...
+				// This is a logical separation and also reduces the risk of Filesystem-overload
+				// due to too many files in the same directory
+				const storageFileName = path.join(nft.contract.csn, fileHash)
+				const targetFile = path.join(STORAGE_DIR, storageFileName)
+				const targetDir =path.dirname(targetFile)
+
+				// Create contract-directory in case it does not exist
+				if(!existsSync(targetDir)) {
+					mkdirSync(targetDir) 
+				}
```
Comment (mologie) [inline pages/api/internal/assets/[anchor]/[assetType]/index.js:165]: This if+mkdir has a TOCTOU issue, and will throw an exception if you're unlucky with parallel uploads. Never check whether a directory exists and then create it if not. Instead, always attempt to create it and catch the kernel's EEXISTS response. The kernel has an atomic view on the filesystem.

File: pages/api/internal/assets/[anchor]/[assetType]/index.js [hunk 5]
```diff
@@ -114,22 +115,27 @@ export default async function handle(req, res) {
...
-	const contract = nft.contract
 
 	// TODO: What to do with assets that aren't attached to any other NFT?
 	// Should this clean up run on an async job?
 	await dropAssetsFromNFT(nft)
 
 	const form = new formidable.IncomingForm()
+	// This is a temporary directory for uploads
+	// It allows us to cache files, but at the same time is isolated from the system's /tmp
+	// this should prevent Arbitrary Code Execution attacks via Image-Uploads.
```
Comment (mologie) [inline pages/api/internal/assets/[anchor]/[assetType]/index.js:126]: I'd drop this comment, it's quite strange to read. Freezing /tmp or wherever the JIT cache is written to during build, so that it cannot be overwritten, prevents arbitrary code execution attacks. Changing the upload directory does not. It's just a necessary consequence of other locations being read-only (and also speeds up uploads a lot by allowing a rename op for completing an upload).

File: pages/api/internal/assets/[anchor]/[assetType]/index.js [hunk 6]
```diff
@@ -140,17 +146,31 @@ export default async function handle(req, res) {
...
 			return res.json({
 				existingAsset
 			})
 		} else {
 			try {
-				writeFileSync(path.join(STORAGE_DIR, fileHash), fileContent)
+				// Split files per Smart contract. 
+				// This is a logical separation and also reduces the risk of Filesystem-overload
+				// due to too many files in the same directory
+				const storageFileName = path.join(nft.contract.csn, fileHash)
```
Comment (mologie) [inline pages/api/internal/assets/[anchor]/[assetType]/index.js:158]: This bit is confusing: There is a database field (and this one) called storageFile**Name**, but it's not a name but a relative path. I'd rename variables here, and also refactor computation of `targetDir` to avoid the `dirname` call -- you know the directory already.

File: pages/api/v1/assets/[asset_hash]/index.js [hunk 7]
```diff
@@ -26,7 +26,8 @@ export default async function handle(req, res) {
 			return res.status(404).json({ message: 'Asset does not exist on our records' })
 		}
 
-		const filePath = path.join(process.cwd(), "nftdata", asset.fileName)
+		const STORAGE_DIR = process.env.STORAGE_DIR
+		const filePath = path.join(STORAGE_DIR, asset.fileName)
```
Comment (mologie) [inline pages/api/v1/assets/[asset_hash]/index.js:30]: Adding to the storage path comment above it might be unexpected that `asset.fileName` is in fact not a file name but a path relative to `STORAGE_DIR`.

File: pages/api/internal/assets/[anchor]/[assetType]/index.js (hunk 4 above)
Comment (tbergmueller) [reply pages/api/internal/assets/[anchor]/[assetType]/index.js:165]: will use the `recursive` approach, which corresponds to `mkdir -p`, which AFAIK solves for this issue
https://nodejs.org/api/fs.html#fsmkdirsyncpath-options

File: pages/api/internal/assets/[anchor]/[assetType]/index.js (hunk 1 above)
Comment (tbergmueller) [reply pages/api/internal/assets/[anchor]/[assetType]/index.js]: Noted for later: https://github.com/authenticvision/digitalsoul/issues/42

File: pages/api/internal/assets/[anchor]/[assetType]/index.js (hunk 3 above)
Comment (tbergmueller) [reply pages/api/internal/assets/[anchor]/[assetType]/index.js:135]: Noted for later: https://github.com/authenticvision/digitalsoul/issues/42

File: pages/api/internal/assets/[anchor]/[assetType]/index.js (hunk 6 above)
Comment (tbergmueller) [reply pages/api/internal/assets/[anchor]/[assetType]/index.js]: Removed https://github.com/authenticvision/digitalsoul/pull/41/commits/8807190ea224f95c7a949f5f541f4b70aea8b306

File: pages/api/internal/assets/[anchor]/[assetType]/index.js (hunk 5 above)
Comment (tbergmueller) [reply pages/api/internal/assets/[anchor]/[assetType]/index.js]: Dropped in the course of https://github.com/authenticvision/digitalsoul/pull/41/commits/8807190ea224f95c7a949f5f541f4b70aea8b306

File: pages/api/internal/assets/[anchor]/[assetType]/index.js (hunk 4 above)
Comment (tbergmueller) [reply pages/api/internal/assets/[anchor]/[assetType]/index.js]: Done in the course of https://github.com/authenticvision/digitalsoul/pull/41/commits/8807190ea224f95c7a949f5f541f4b70aea8b306

File: pages/api/v1/assets/[asset_hash]/index.js (hunk 7 above)
Comment (tbergmueller) [reply pages/api/v1/assets/[asset_hash]/index.js]: There is a "good" reason for that; 
docker-compose uses the build-stage directly for development (to build on the fly), while production uses the runner. 

Will follow-up on this in #19

File: Dockerfile (hunk 2 above)
Comment (tbergmueller) [reply Dockerfile:29]: There is a "good" reason for that; 
docker-compose uses the build-stage directly for development (to build on the fly), while production uses the runner. 

Will follow-up on this in #19

**Comment by tbergmueller** [comment]
Thanks @mologie for review - Either followed your suggestions or noted them as TODOs for later in #42 . Please resolve conversations if good for you

Can either you or @pedrolucasp approve, s.t. we can merge? Maybe I was a bit too early too strict with the gitflow :D

File: pages/api/internal/assets/[anchor]/[assetType]/index.js (hunk 3 above)
Comment (mologie) [reply pages/api/internal/assets/[anchor]/[assetType]/index.js:135]: Fine with me, nitpicking tho: Your description in #42 is "Stream files during upload instead of reading them to memory" but it's after the upload and it should probably mention that this is to fix excessive memory usage during file hashing.

File: Dockerfile (hunk 2 above)
Comment (mologie) [reply Dockerfile:29]: Eek

**Review by mologie — APPROVED** [review]
